services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: loganalyser
      MYSQL_USER: loganalyser
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 2s
      timeout: 5s
      retries: 15
