[settings]
poll_interval_secs = 3

[storage]
storage_type = "sqlite"
# connection_string = "mysql://user:pass@localhost/loganalyser"
connection_string = "/home/ben/loganalyser/events.db"

[defaults]
timestamp_format = "%Y-%m-%d %H:%M:%S"

[components]
timestamp = '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
ref = '(?P<ref>[A-Z]{3})'
__ = '\s+'

[[parsers]]
name = "log1"
glob = "/home/ben/loganalyser/*.log"
type = "single"
pattern = '{{timestamp}}{{__}}(?P<data>.*)'

[[parsers]]
name = "log2"
glob = "/home/ben/loganalyser/*.log"
type = "span"
start_pattern = '{{timestamp}}{{__}}{{ref}}{{__}}START'
end_pattern = '{{timestamp}}{{__}}{{ref}}{{__}}END'
reference_fields = ["ref"]
nested = [
    { name = "innerlog1", type = "single", pattern = '{{timestamp}}{{__}}{{ref}}{{__}}SOMETHING HAPPENED' },
]
